# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # set to false, if you do NOT want to check the correct VirtualBox Guest Additions version when booting this box
  if defined?(VagrantVbguest::Middleware)
    config.vbguest.auto_update = true
  end

  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", "4096"]
  end

  config.vm.define :elasticstack do |elasticstack_config|

    elasticstack_config.vm.box = "ubuntu/trusty64"
    elasticstack_config.vm.hostname = 'elasticstack' 
    elasticstack_config.vm.network :private_network, ip: "172.28.1.10" 
    elasticstack_config.vm.network :forwarded_port, guest: 5601, host: 5601
    elasticstack_config.vm.network :forwarded_port, guest: 9200, host: 9200
    #elasticstack_config.vm.network :forwarded_port, guest: 5044, host: 5044

    elasticstack_config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    elasticstack_config.vm.provision :shell, path: "provision-elasticsearch.sh"

    elasticstack_config.vm.provision :shell, path: "provision-logstash.sh"

    elasticstack_config.vm.provision :shell, path: "provision-kibana.sh"
  end
 
end

