# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Fix Vagrant 1.8.5 bug
  # config.ssh.insert_key = false

  # set to false, if you do NOT want to check the correct VirtualBox Guest Additions version when booting this box
  if defined?(VagrantVbguest::Middleware)
    config.vbguest.auto_update = true
  end

  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", "512"]
  end

  config.vm.define :demo_deteccion do |demo_deteccion_config|
    demo_deteccion_config.vm.box = "ubuntu/trusty64"
    demo_deteccion_config.vm.hostname = 'demo' 
    demo_deteccion_config.vm.network :private_network, ip: "172.28.1.13" 
    demo_deteccion_config.vm.network :forwarded_port, guest:5000 , host: 1234

    demo_deteccion_config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    demo_deteccion_config.vm.provision :shell, path: "provision-demo.sh"
  end
end

